Loaded: ./exceptions.s
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is false :(
var is false :(
var is false :(
var is false :(
  Exception 4  [Address error in inst/data fetch]  occurred and ignored
var is false :(
var is false :(
var is false :(
var is false :(
var is false :(
  Exception 4  [Address error in inst/data fetch]  occurred and ignored
var is false :(
var is false :(
var is false :(
var is false :(
var is false :(
  Exception 4  [Address error in inst/data fetch]  occurred and ignored
var is false :(
var is false :(
var is false :(
var is false :(
var is false :(
  Exception 4  [Address error in inst/data fetch]  occurred and ignored
var is false :(
var is false :(
var is false :(
var is false :(
var is false :(
  Exception 4  [Address error in inst/data fetch]  occurred and ignored
var is false :(
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is true :)
var is false :(
var is false :(
var is false :(
var is false :(
  Exception 4  [Address error in inst/data fetch]  occurred and ignored
var is false :(
var is false :(
var is false :(
var is false :(
var is false :(
var is false :(
var is false :(
var is false :(
var is false :(
var is false :(
